-- Drop existing tables
DROP TABLE IF EXISTS "Posizionamento" CASCADE ;
DROP TABLE IF EXISTS "Posizione" CASCADE ;
DROP TABLE IF EXISTS "Spazio" CASCADE ;
DROP TABLE IF EXISTS "Cliente" CASCADE ;
DROP TABLE IF EXISTS "Ordine" CASCADE ;
DROP TABLE IF EXISTS "Pianta" CASCADE ;
DROP TABLE IF EXISTS "Operatore" CASCADE;
DROP TABLE IF EXISTS "Settore" CASCADE;
DROP TABLE IF EXISTS "Operazione" CASCADE;
DROP TABLE IF EXISTS "Admin" CASCADE;

DROP TABLE IF EXISTS "Sensore" CASCADE;
DROP TABLE IF EXISTS "Attuatore" CASCADE;

